/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JFileChooser;
import java.io.File; 
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author sudar
 */

public class home extends javax.swing.JFrame {
    
    class node
    {
        String data;
        node next;
        node skip;
        
        node(String a)
        {
            data=a;
            next=null;
            skip=null;
        }
        
        node()
        {
            data="";
            next=null;
            skip=null;
        }
        
        
    }

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Add Documents");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setToolTipText("");

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(this);
        File selectedFile=null;
        if (result == JFileChooser.APPROVE_OPTION) {
            selectedFile = fileChooser.getSelectedFile();
        }
        if(selectedFile!=null)
        {
            try {
                readfilecontents(selectedFile.toString());
            } catch (IOException ex) {
                System.out.println("Exception at insert: "+ex);
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String query;
        if(jTextField1.getText()!="")
        {
            query=jTextField1.getText();
            try {
                operatequery(query);
            } catch (IOException ex) {
                System.out.println("Exception at search: "+ex);
            }
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed
    
    
HashMap<String,node> map=new HashMap<>();
    
    public void operatequery(String q) throws IOException
    {
        String[] qs=q.split(" ");
        if(qs.length==1)
        {
            printlist(findlist(qs[0]));
            return;
        }
        List<String> l=matchlist(findlist(qs[0]),findlist(qs[1]));
        for(int i=2;i<qs.length;i++)
        {
            l=matchlist(l,findlist(qs[i]));
        }
        printlist(l);
    }
    
    public List<String> matchlist(List<String> l1,List<String> l2)
    {
        
        int i=0,j=0;
        List<String> r=new ArrayList<>();
        while(i<l1.size() && j<l2.size())
        {
            String cur1=l1.get(i);
            String cur2=l2.get(j);
            if(cur1.equals(cur2))
            {
                r.add(cur2);
                i++;
                j++;
            }
            else if(cur1.compareTo(cur2)<0)
            {
                i++;
            }
            else
                j++;
            
        }
        return r;
    }

    public void printMap(HashMap mp) {
        Iterator it = mp.entrySet().iterator();
        while (it.hasNext()) {
            Map.Entry pair = (Map.Entry)it.next();
            System.out.print(pair.getKey()+" -> ");
            for(node temp=(node) pair.getValue();;temp=temp.next)
            {
                if(temp!=null)
                    System.out.print(temp.data+" -> ");
                if(temp.next==null)
                    break;
            }

            System.out.println();

        }
        System.out.println("________________________________________");
    }
    
    void printlist(List<String> list) throws IOException
    {
        String output="";
        for(int i=0;i<list.size();i++)
        {
            output+="File name:"+list.get(i)+"\nContents of file: \n";
            List<String> lines = Files.readAllLines(Paths.get(list.get(i)));
            for(int j=0;j<lines.size();j++)
                output+=lines.get(j)+"\n";
            output+="\n";
        }
        if(output.equals(""))
            output="Not Found";
            
        jTextArea1.setText(output);
    }
    
    public List findlist(String query) throws IOException
    {
        List<String> l=new ArrayList<String>();
        if(map.containsKey(query))
        {
            node tempn=map.get(query);
            while(tempn!=null)
            {
                //output+="File name:"+tempn.data+"\nContents of file: \n";
                //List<String> lines = Files.readAllLines(Paths.get(tempn.data));
                //for(int j=0;j<lines.size();j++)
                //    output+=lines.get(j)+"\n";
                //output+="\n";
                
                l.add(tempn.data);
                tempn=tempn.next;
                
                
            }
        }
       
        return l;
    }
    public void readfilecontents(String path) throws IOException
    {
        
        List<String> lines = Files.readAllLines(Paths.get(path));

        for(int i=0;i<lines.size();i++)
        {
            StringTokenizer st=new StringTokenizer(lines.get(i));
            while(st.hasMoreTokens())
            {
                
                String stemp=st.nextToken();
                boolean flag=true;
                
                
                if(map.containsKey(stemp))
                {
                    int k=0;
                    node curr=map.get(stemp);
                    
                    if(curr.data.compareTo(path)>0 && curr.data.compareTo(path)!=0)
                    {
                        map.put(stemp,new node(path));
                        map.get(stemp).next=curr;
                        flag=false;
                    }
                    
                    while(curr.skip!=null )
                    {
                        if(curr.data.equals(path))
                        {
                            flag=false;
                            break;
                        }
                        if(curr.skip==null || curr.skip.data.compareTo(path)>0)
                            break;
                        
                        curr=curr.skip;
                    }
                    node skipassign=curr;
                    while(curr.next!=null )
                    {
                        if(curr.data.equals(path))
                        {
                            flag=false;
                            break;
                        }
                        if(curr.next==null || curr.next.data.compareTo(path)>0)
                            break;
                        curr=curr.next;
                        k++;
                        if(k==5)
                        {
                            skipassign.skip=curr;
                            k=0;
                            skipassign =curr;
                        } 
                    }
                    
                    if(!curr.data.equals(path) && flag)
                    {
                        node tempnode=curr.next;
                        curr.next=new node(path);
                        curr.next.next=tempnode;
                    }
                        

                }
                else
                {
                    map.put(stemp, new node(path));
                }

            }
        }
        
        
        //
        
        printMap(map);
        
        //
        
        
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
